version: "2"
services:
  app:
    build: .
    command: "bundle exec rails s -p 34567 -b '0.0.0.0'"
    ports:
      - "34567:34567"
    volumes:
      - ./sqlite:/app/sqlite
    tty: true
    stdin_open: true
