# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 020a629cdf2e8c34ddf68ec50ea0b31fe45435d5391e305269b107ebb4d1f5b073540c5e9d20157bbf52af2630ebcc8f340df93a3e465b8a2aa287b90b92064a

test:
  secret_key_base: f1891b66e840c3196523e77756dd3f08b6c73348fcd4eb15e4d238c13dc2915d7e05ec3c08ead28236012c6ec64c5db573c7a8a7e01386e03a541999409c9e1b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
